version: '3'

services:
  mongo:
    image: "mongo:4"
    command: mongod --bind_ip_all
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    depends_on: 
      - "mongo"
    ports:
      - 27080:8081
